<?php

/**
 * @file mailchimp_webhook.module
 */

/**
 * Implements hook_menu
 *
 * Show a list of potential webhook campaign endpoint URLs to be included
 * in the MailChimp.com-side configuration
 */
function mailchimp_campaigngrab_menu() {
  $items = array();

  $items['admin/config/services/mailchimp/campaigngrab'] = array(
    'title' => 'Webhook URL',
    'description' => 'Webhook URL to which MailChimp can post campaigns',
    'page callback' => 'mailchimp_campaigngrab_webhookurl_page',
    'access arguments' => array('administer mailchimp'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'mailchimp_campaigngrab.admin.inc',
    'weight' => -10
  );

  return $items;
}

/**
 * Implements hook_mailchimp_webhook
 *
 * If the webhook is a campaign send, create a record of that campaign being sent
 */
function mailchimp_campaigngrab_mailchimp_webhook($type, $data) {
  if ($type == 'campaign' && $data['status'] == 'sent') {
    $q = mailchimp_get_api_object();
    // mailchimp_campaigns expects $template to be a drupal render array
    // so we grab a mailchimp-looking format and modify the template values:
    // 'template' => array('value' => $template, 'format' => $mc_format)
    $mc_format = (array_key_exists('mailchimp_campaign', filter_formats())) ? 'mailchimp_campaign' : 'plain_text';
    $template = $q->campaignTemplateContent($data['id']);
    $renderable_template = array();
    foreach ($template as $fieldname => $fieldvalue) {
      $renderable_template[$fieldname]['format'] = $mc_format;
      $renderable_template[$fieldname]['value'] = $fieldvalue;
    }
    $campaign = entity_create('mailchimp_campaign', array(
      'mc_campaign_id' => $data['id'],
      'template' => $renderable_template,
      'subject' => $data['subject'],
    ));
    mailchimp_campaign_save($campaign);
  }
}
